const MAX_USER_PUBLICATION = 25;
const MAX_NUMBER_AVATAR = 6;
const MIN_NUMBER_LIKES = 15;
const MAX_NUMBER_LIKES = 200;
const MAX_NUMBER_COMMENTS = 5;
const MIN_ELEMENTS = 1;

const STEP_SIZE_PHOTO = 25;
const MIN_PHOTO_SIZE = 25;
const MAX_PHOTO_SIZE = 100;

const MAX_HASHTAG_LENGTH = 20;
const MAX_HASHTAG_COUNT = 5;
const MAX_COMMENT_LENGTH = 140;

const DELAY = 500;
const VISIBLE_COMMENTS = 5;

export {
  MAX_USER_PUBLICATION,
  MAX_NUMBER_AVATAR,
  MIN_NUMBER_LIKES,
  MAX_NUMBER_LIKES,
  MAX_NUMBER_COMMENTS,
  MIN_ELEMENTS,
  STEP_SIZE_PHOTO,
  MIN_PHOTO_SIZE,
  MAX_PHOTO_SIZE,
  MAX_HASHTAG_LENGTH,
  MAX_HASHTAG_COUNT,
  MAX_COMMENT_LENGTH,
  DELAY,
  VISIBLE_COMMENTS
};
